### ISSUE TITLE
Cannot add user constraints

### ISSUE THREAD

**Issue by Knight-Ops** [alchitry/Alchitry-Labs#2]
When I attempt to add a user constraint to a project using the `New Constraint...` option, I get an error stating that the creation of the User Constraint file failed.

**Comment by alchitry** [comment]
Can you explain a bit more? What board is the project set to? I assume you are talking about the new file dialog?

**Comment by Knight-Ops** [comment]
Steps to reproduce:
- New Project (Workspace is default Documents\alchitry, Board is Alchitry Au, Language is Lucid, From Example is Base Project)
- Right Click Constraints Drop down
- Select `New Constraint...`
- Select User Constraint (This adds .acf as file extension)
- Name the file
- Select `Create File`
- Error Occurs -> `Could not create constraint file!`

That is about all the information that I can provide as I have never been able to properly create these files. I have created them in the Alchitry Labs directory structure and added them to lib.xml successfully, but never gotten them added to the `Constraints` section.

**Comment by alchitry** [comment]
What operating system are you on? Do you see anything relevant in the log file (usually in the same directory as the executable)? Do you have write permissions for that folder?

**Comment by alchitry** [comment]
Also just thought of this, is there a constraints folder in the project directory?

**Comment by alchitry** [comment]
Version 1.0.3 fixes this bug. It was caused by the Windows installer ignoring the empty constraint directory in the project templates. The fix was to create the directory if needed.
