### ISSUE TITLE
Doesn't support Mojo v2 board

### ISSUE THREAD

**Issue by ebissett** [alchitry/Alchitry-Labs#22]
I wasn't able to get my Mojo v2 board working with Alchitry Labs after going through the Bootloader and FPGA Loader upgrade procedure (https://alchitry.com/blogs/tutorials/flashing-the-bootloader).

The Alchitry IDE just keeps saying "Couldn't find device!".  It has no trouble seeing my friend's Alchitry CU board.  I do not own a Mojo v3 for comparison.

I believe the reason the IDE cannot see the v2 is that the IDE appears to have the USB Product ID coded to the wrong value for the Mojo v2 board.  lsusb shows my board ID as 29dd:8000. The Mojo.java file has the Product ID hardcoded as 8001 which I assume is the Mojo v3 value.

I haven't found any literature indicating the v2 boards have been deprecated, just that they are slower.

**Comment by alchitry** [comment]
There shouldn't be any differences between the two boards in terms of them working with the IDE. The only major change from V2 to V3 was the bigger microcontroller and a more robust USB port (V2's tended to break). 1.2.7 might fix your issue or it may be an incompatible firmware problem.
