### ISSUE TITLE
Build output is not easy to be copied on Linux

### ISSUE THREAD

**Issue by kitlaan** [alchitry/Alchitry-Labs#8]
You're basically required to do a left-click and drag up (and up, and up) to select all the content, rather than using a hotkey like CTRL-A.

Alternatively (or in addition), it might be useful to have the build output saved to a logfile so it's still around when something overwrites the window contents.

**Comment by alchitry** [comment]
CTRL+A hotkey added to 1.0.4 to select all.

The logs can be found in the work directory. The various builders save them. For example work/vivado/projName/projName.runs/synth_1/runme.log is the synthesis log for Vivado.

**Comment by kitlaan** [comment]
Do all the toolchains save logs, or is it just specific ones?

The IceStorm programs doesn't seem to save (consistently, or at all).

**Comment by alchitry** [comment]
I think you are right in saying that it doesn't save a lot. I added a new issue to remind me to add a log file to 1.0.5.
